In [1]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

engine = create_engine(
    "mysql+pymysql://root:Rakhi@localhost/securelife_insurance"
)

branches = pd.read_sql('select * from branches;', engine)
agents = pd.read_sql('select * from agents;', engine)
claim_investigations = pd.read_sql('select * from claim_investigations;', engine)
claims = pd.read_sql('select * from claims;', engine)
customer_complaints = pd.read_sql('select * from customer_complaints;', engine)
customers = pd.read_sql('select * from customers;', engine)
payments = pd.read_sql('select * from payments;', engine)
policies = pd.read_sql('select * from policies;', engine)
providers = pd.read_sql('select * from providers;', engine)
policy_renewals = pd.read_sql('select * from policy_renewals;', engine)

print('Tables Loaded Successfully')

Tables Loaded Successfully

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10,5)

In [3]:
customers.head()

,customer_id,customer_name,gender,age,city,state,occupation,annual_income,customer_since,customer_risk_category
0,100001,Vijay Chopra,Female,30,Jaipur,Tamil Nadu,Business,407714.06,2022-04-26,Low
1,100002,Deepa Chopra,Female,25,Nagpur,Uttar Pradesh,Business,2158661.55,2021-01-11,Low
2,100003,Priya Verma,Male,23,Ranchi,Delhi,Self-Employed,2168250.14,2019-06-28,None
3,100004,Kiran Sharma,Female,72,Nagpur,Tamil Nadu,Business,1944074.04,2019-12-10,Medium
4,100005,Neha Rao,Female,46,Noida,Gujarat,Salaried,2209038.33,2023-12-06,Low

In [4]:
# =========================
# CUSTOMERS TABLE CLEANING
# =========================
customers = customers.drop_duplicates()

# Gender cleaning
customers['gender'] = (
    customers['gender']
    .astype(str)
    .str.strip()
    .str.lower()
)

customers['gender'] = customers['gender'].replace({
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    'other': 'Other',
    'nan': 'Other'
})

customers['gender'] = customers['gender'].fillna('Other')

# Age cleaning
customers['age'] = customers['age'].fillna(customers['age'].median())

customers.loc[
    (customers['age'] < 1) |
    (customers['age'] > 100),
    'age'
] = customers['age'].median()

# Income cleaning
customers['annual_income'] = customers['annual_income'].fillna(
    customers.groupby('occupation')['annual_income'].transform('median')
)

# Name cleaning
customers['customer_name'] = (
    customers['customer_name']
    .fillna('Unknown')
    .astype(str)
    .str.strip()
)
numeric_cols = [
    'customer_id',
    'annual_income'
]

for col in numeric_cols:

    customers.loc[
        customers[col] <= 0,
        col
    ] = 0
    
# Final null removal
customers = customers.fillna('Unknown')

In [5]:
customers.head()

,customer_id,customer_name,gender,age,city,state,occupation,annual_income,customer_since,customer_risk_category
0,100001,Vijay Chopra,Female,30,Jaipur,Tamil Nadu,Business,407714.06,2022-04-26,Low
1,100002,Deepa Chopra,Female,25,Nagpur,Uttar Pradesh,Business,2158661.55,2021-01-11,Low
2,100003,Priya Verma,Male,23,Ranchi,Delhi,Self-Employed,2168250.14,2019-06-28,Unknown
3,100004,Kiran Sharma,Female,72,Nagpur,Tamil Nadu,Business,1944074.04,2019-12-10,Medium
4,100005,Neha Rao,Female,46,Noida,Gujarat,Salaried,2209038.33,2023-12-06,Low

In [6]:
# Export all rows to SQL table in chunks
customers.to_sql(
    'customers_cleaned',
    engine,
    if_exists='replace',
    index=False,
    chunksize=5000
)

100001

In [7]:
policies.head()

,policy_id,customer_id,policy_type,policy_start_date,policy_end_date,premium_amount,coverage_amount,policy_status,agent_id,branch_id
0,5000001,123511,Motor,2021-10-17,2023-03-25,28640.44,3578432.84,Cancelled,9482,808
1,5000002,132647,Life,2024-10-06,2025-02-11,12218.48,232698.63,Cancelled,15307,604
2,5000003,153939,Travel,2020-12-20,2021-04-11,33980.68,1556367.94,Active,16017,517
3,5000004,145551,Health,2021-09-30,2022-02-25,28322.40,2960824.68,Expired,15836,619
4,5000005,153199,Property,2020-07-09,2024-01-29,78326.02,679889.59,Active,10019,558

In [8]:
# ========================
# POLICIES TABLE CLEANING
# ========================

policies = policies.drop_duplicates()

# Policy type
policies['policy_type'] = (
    policies['policy_type']
    .fillna('Unknown')
    .astype(str)
    .str.strip()
    .str.title()
)

# Policy status
policies['policy_status'] = (
    policies['policy_status']
    .fillna('Unknown')
    .astype(str)
    .str.strip()
    .str.title()
)
numeric_cols = [
    'policy_id',
    'customer_id',
    'agent_id',
    'branch_id'
]

for col in numeric_cols:
    policies.loc[
        policies[col] <= 0,
        col
    ] = 0
# Fill missing premium_amount using median based on policy_type
policies['premium_amount'] = policies['premium_amount'].fillna(
    policies.groupby('policy_type')['premium_amount'].transform('median')
)

# Fill remaining nulls with overall median
policies['premium_amount'] = policies['premium_amount'].fillna(
    policies['premium_amount'].median()
)

# Date conversion
policies['policy_start_date'] = pd.to_datetime(
    policies['policy_start_date'],
    errors='coerce'
)

policies['policy_end_date'] = pd.to_datetime(
    policies['policy_end_date'],
    errors='coerce'
)

# Find invalid dates
mask = policies['policy_end_date'] < policies['policy_start_date']

# Make invalid dates null
policies.loc[
    mask,
    ['policy_start_date', 'policy_end_date']
] = pd.NaT

# Drop rows with null dates
policies = policies.dropna(
    subset=['policy_start_date', 'policy_end_date']
)

# Final null removal
policies = policies.fillna('Unknown')

In [9]:
policies.isnull().sum()

policy_id            0
customer_id          0
policy_type          0
policy_start_date    0
policy_end_date      0
premium_amount       0
coverage_amount      0
policy_status        0
agent_id             0
branch_id            0
dtype: int64

In [10]:
# Export
policies.to_sql(
    'policies_cleaned',
    engine,
    if_exists='replace',
    index=False
)

167178

In [11]:
claims.head()

,claim_id,policy_id,customer_id,claim_type,claim_amount,claim_submission_date,incident_date,claim_status,fraud_flag,settlement_days,provider_id
0,9000001,5175095,125658.0,Death,146998.43,2022-07-03,2023-06-12,approved,b'\x00',2,6395
1,9000002,5066916,170553.0,Hospitalization,494346.41,2023-05-16,2022-06-06,Pending,b'\x00',11,6149
2,9000003,5107802,104133.0,Accident,130492.85,2022-07-17,2021-05-22,Pending,b'\x00',41,5850
3,9000004,5016219,187926.0,Death,304982.65,2024-03-01,2023-06-01,Pending,b'\x00',26,4563
4,9000005,5201478,104394.0,Hospitalization,116748.92,2021-12-18,2023-06-15,Pending,b'\x00',-3,6163

In [12]:
claims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151014 entries, 0 to 151013
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   claim_id               151014 non-null  int64
 1   policy_id              151014 non-null  int64
 2   customer_id            148042 non-null  float64
 3   claim_type             151014 non-null  object
 4   claim_amount           151014 non-null  float64
 5   claim_submission_date  151014 non-null  object
 6   incident_date          151014 non-null  object
 7   claim_status           151014 non-null  object
 8   fraud_flag             146469 non-null  object
 9   settlement_days        151014 non-null  int64
 10  provider_id            151014 non-null  int64
dtypes: float64(2), int64(4), object(5)
memory usage: 12.7+ MB

In [110]:

claims['fraud_flag'] = (
    claims['fraud_flag']
    .apply(
        lambda x: 1 if x == b'\x01' else 0
    )
)

# Check values
print(claims['fraud_flag'].unique())

# Count values
print(claims['fraud_flag'].value_counts())

[0 1]
fraud_flag
0    132562
1     18454
Name: count, dtype: int64

In [13]:
# ======================
# CLAIMS TABLE CLEANING
# ======================

claims = claims.drop_duplicates()

# Claim status
claims['claim_status'] = (
    claims['claim_status']
    .fillna('Unknown')
    .astype(str)
    .str.strip()
    .str.title()
)

# Claim amount
claims['claim_amount'] = claims['claim_amount'].fillna(
    claims['claim_amount'].median()
)

claims['claim_amount'] = claims['claim_amount'].fillna(0)

# Dates
claims['claim_submission_date'] = pd.to_datetime(
    claims['claim_submission_date'],
    errors='coerce'
)

claims['incident_date'] = pd.to_datetime(
    claims['incident_date'],
    errors='coerce'
)

# Numeric columns
numeric_cols = [
    'policy_id',
    'customer_id',
    'claim_id',
    'claim_amount',
    'settlement_days'
]

for col in numeric_cols:

    # Convert to numeric
    claims[col] = pd.to_numeric(
        claims[col],
        errors='coerce'
    )

    claims[col] = claims[col].fillna(0)

    # Replace negative values
    claims.loc[
        claims[col] < 0,
        col
    ] = 0

# Fraud flag cleaning
claims['fraud_flag'] = (
    claims['fraud_flag']
    .astype(str)
    .str.strip()
)

claims['fraud_flag'] = claims['fraud_flag'].apply(
    lambda x: 1 if x in [
        '1',
        '\x01',
        "b'\\x01'",
        'True'
    ] else 0
)

claims['fraud_flag'] = claims['fraud_flag'].astype(int)

# Fill nulls only for object columns
object_cols = claims.select_dtypes(include='object').columns

claims[object_cols] = claims[object_cols].fillna('Unknown')

# Check values
print(claims['fraud_flag'].unique())

# Count values
print(claims['fraud_flag'].value_counts())

[0 1]
fraud_flag
0    132559
1     18455
Name: count, dtype: int64

In [14]:
# Export
claims.to_sql(
    'claims_cleaned',
    engine,
    if_exists='replace',
    index=False,
    chunksize=5000
)

151014

In [15]:
claims['fraud_flag'].value_counts(dropna=False)

fraud_flag
0    132559
1     18455
Name: count, dtype: int64

In [16]:
claims['fraud_flag'].unique()

array([0, 1])

In [17]:
payments

,payment_id,policy_id,claim_id,payment_type,payment_amount,payment_date,payment_method,payment_status,transaction_reference
0,7200001,5031412,9056654.0,Premium,179230.46,2024-03-30,UPI,Success,TXN_8IKUDR
1,7200002,5105890,9089138.0,Claim Settlement,413478.37,2024-10-19,Bank Transfer,Success,None
2,7200003,5206228,NaN,Refund,391272.22,2024-10-18,UPI,Pending,TXN_BYDRFI
3,7200004,5117085,NaN,Refund,470886.44,2021-06-04,Bank Transfer,Failed,TXN_9FYGUQ
4,7200005,5125420,9070798.0,Claim Settlement,365862.78,2024-02-08,UPI,Failed,TXN_96X39D
...,...,...,...,...,...,...,...,...,...
120716,7513395,5213333,9133630.0,Premium,42755.99,2023-11-25,UPI,Reversed,TXN_8Y3CYX
120717,7513412,5173860,9053754.0,Claim Settlement,492446.23,2022-05-16,Bank Transfer,Success,TXN_AFA8OE
120718,7513588,5129173,9143985.0,Claim Settlement,240389.72,2023-01-10,Card,Reversed,TXN_HN4OC
120719,7513619,5243673,9130008.0,Refund,479318.56,2024-08-23,Bank Transfer,Reversed,TXN_6268PD
120720,7513751,5050366,9130612.0,Refund,158265.37,2021-03-05,UPI,Failed,TXN_9JG7KM

In [18]:
# ========================
# PAYMENTS TABLE CLEANING
# ========================

payments = (
    payments.drop_duplicates()
)

# ========================
# HANDLE NULL VALUES
# ========================

# Fill payment_amount null values
# using median grouped by payment_type

payments['payment_amount'] = (
    payments.groupby('payment_type')['payment_amount']
    .transform(
        lambda x: x.fillna(x.median())
    )
)

# Fill remaining null values with overall median
payments['payment_amount'] = (
    payments['payment_amount']
    .fillna(
        payments['payment_amount'].median()
    )
)

# Final fallback
payments['payment_amount'] = (
    payments['payment_amount']
    .fillna(0)
)

# claim_id null handling
payments['claim_id'] = (
    payments['claim_id']
    .fillna(0)
)

# payment_type null handling
payments['payment_type'] = (
    payments['payment_type']
    .fillna('Unknown')
)

# ========================
# HANDLE NEGATIVE VALUES
# ========================

numeric_cols = [
    'payment_id',
    'policy_id',
    'claim_id',
    'payment_amount'
]

for col in numeric_cols:


    # Replace negative values with 0
    payments.loc[
        payments[col] < 0,
        col
    ] = 0

# Fill any remaining missing categorical values
payments = (
    payments.fillna('Unknown')
)

# ========================
# CHECK NULL VALUES
# ========================

print("Null values after cleaning:\n")

null_values = payments.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# ========================
# CHECK NEGATIVE VALUES
# ========================

print("\nChecking negative values:\n")

numeric_check = payments.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_check:

    negative_count = (
        payments[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    payments[numeric_check] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# ========================
# SAVE CLEANED TABLE
# ========================

payments.to_sql(
    'payments_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

payment_id               0
policy_id                0
claim_id                 0
payment_type             0
payment_amount           0
payment_date             0
payment_method           0
payment_status           0
transaction_reference    0
dtype: int64

No null values present after cleaning.

Checking negative values:

payment_id : 0 negative values
policy_id : 0 negative values
claim_id : 0 negative values
payment_amount : 0 negative values

No negative values present after cleaning.

120721

In [19]:
claim_investigations.head()

,investigation_id,claim_id,investigation_start_date,investigation_end_date,investigator_name,risk_score,investigation_result,evidence_count,remarks
0,8100001,9978980,2023-09-09,2022-10-22,Anita Patel,87,Inconclusive,8,None
1,8100002,9007736,2023-06-09,2021-01-24,Rajesh Verma,20,Not Fraud,7,Policy taken recently before claim
2,8100003,9041665,2023-03-06,2022-04-17,None,78,Not Fraud,-3,Policy taken recently before claim
3,8100004,9009506,2022-09-05,2022-07-25,Siddharth Sharma,17,Not Fraud,8,Provider inflated claim amount
4,8100005,9038603,2023-01-27,2022-02-07,Anita Reddy,23,Inconclusive,7,Third party verification pending

In [20]:
# =================================
# CLAIM INVESTIGATIONS CLEANING
# =================================

claim_investigations = (
    claim_investigations.drop_duplicates()
)

# Investigation result
claim_investigations['investigation_result'] = (
    claim_investigations['investigation_result']
    .fillna('Unknown')
)

# Evidence count
claim_investigations['evidence_count'] = (
    claim_investigations['evidence_count']
    .fillna(0)
)

# Convert datatype to integer
claim_investigations['evidence_count'] = (
    claim_investigations['evidence_count']
    .astype(int)
)

# Remarks
claim_investigations['remarks'] = (
    claim_investigations['remarks']
    .fillna('No Remarks')
)

# Risk score
claim_investigations['risk_score'] = (
    claim_investigations['risk_score']
    .fillna(0)
)

# Replace negative risk score with 0
claim_investigations.loc[
    claim_investigations['risk_score'] < 0,
    'risk_score'
] = 0

# Limit maximum risk score to 100
claim_investigations.loc[
    claim_investigations['risk_score'] > 100,
    'risk_score'
] = 100

# Numeric columns
numeric_cols = [
    'investigation_id',
    'claim_id',
    'evidence_count',
    'risk_score'
]

for col in numeric_cols:

    # Replace negative values with 0
    claim_investigations.loc[
        claim_investigations[col] < 0,
        col
    ] = 0

claim_investigations = (
    claim_investigations.fillna('Unknown')
)

# =================================
# CHECK NULL VALUES
# =================================

print("Null values after cleaning:\n")

null_values = claim_investigations.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# =================================
# CHECK NEGATIVE VALUES
# =================================

print("\nChecking negative values:\n")

numeric_check = claim_investigations.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_check:

    negative_count = (
        claim_investigations[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    claim_investigations[numeric_check] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# =================================
# SAVE CLEANED TABLE
# =================================

claim_investigations.to_sql(
    'claim_investigations_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

investigation_id            0
claim_id                    0
investigation_start_date    0
investigation_end_date      0
investigator_name           0
risk_score                  0
investigation_result        0
evidence_count              0
remarks                     0
dtype: int64

No null values present after cleaning.

Checking negative values:

investigation_id : 0 negative values
claim_id : 0 negative values
risk_score : 0 negative values
evidence_count : 0 negative values

No negative values present after cleaning.

35000

In [21]:
agents.head()

,agent_id,agent_name,branch_id,city,agent_experience_years,agent_status,policies_sold,commission_amount,agent_risk_category
0,7001,Arjun Patel_7001,795,Ranchi,28,Suspended,895,314016.66,High
1,7002,Ravi Verma_7002,647,Delhi,19,Active,980,142440.20,Low
2,7003,Sneha Sharma_7003,791,Bhopal,9,Inactive,308,258370.44,High
3,7004,Pooja Sharma_7004,845,Jaipur,25,Inactive,294,101407.27,High
4,7005,Ravi Das_7005,705,Delhi,2,Suspended,614,226613.78,High

In [22]:
# ======================
# AGENTS TABLE CLEANING
# ======================

agents = (
    agents.drop_duplicates()
)

agents['agent_name'] = (
    agents['agent_name']
    .fillna('Unknown')
)

agents['city'] = (
    agents['city']
    .fillna('Unknown')
)

agents['agent_risk_category'] = (
    agents['agent_risk_category']
    .fillna('Unknown')
)

# Numeric columns
numeric_cols = [
    'agent_id',
    'commission_amount'
]

for col in numeric_cols:

    # Replace negative values with 0
    agents.loc[
        agents[col] < 0,
        col
    ] = 0

agents = (
    agents.fillna('Unknown')
)

# ======================
# CHECK NULL VALUES
# ======================

print("Null values after cleaning:\n")

null_values = agents.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# ======================
# CHECK NEGATIVE VALUES
# ======================

print("\nChecking negative values:\n")

numeric_check = agents.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_check:

    negative_count = (
        agents[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    agents[numeric_check] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# ======================
# SAVE CLEANED TABLE
# ======================

agents.to_sql(
    'agents_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

agent_id                  0
agent_name                0
branch_id                 0
city                      0
agent_experience_years    0
agent_status              0
policies_sold             0
commission_amount         0
agent_risk_category       0
dtype: int64

No null values present after cleaning.

Checking negative values:

agent_id : 0 negative values
branch_id : 0 negative values
agent_experience_years : 0 negative values
policies_sold : 0 negative values
commission_amount : 0 negative values

No negative values present after cleaning.

10000

In [23]:
branches.head()

,branch_id,branch_name,city,state,region,branch_manager,opening_date,branch_type,claim_processing_capacity
0,501,Ahmedabad Branch-1,Ahmedabad,Gujarat,West,None,2018-04-18,Rural,842
1,502,Bengaluru Branch-2,Bengaluru,Karnataka,South,Manager_502,2010-01-03,Semi-Urban,489
2,503,Bhopal Branch-3,Bhopal,Madhya Pradesh,Central,Manager_503,2021-08-30,Metro,203
3,504,Bhubaneswar Branch-4,Bhubaneswar,Odisha,East,Manager_504,2011-03-10,Metro,359
4,505,Chandigarh Branch-5,Chandigarh,Punjab,North,Manager_505,2016-07-20,Rural,941

In [24]:
# =========================
# BRANCHES TABLE CLEANING
# =========================

branches = (
    branches.drop_duplicates()
)

branches['branch_name'] = (
    branches['branch_name']
    .fillna('Unknown')
)

branches['city'] = (
    branches['city']
    .fillna('Unknown')
)

branches['state'] = (
    branches['state']
    .fillna('Unknown')
)

# Numeric columns check
numeric_cols = [
    'branch_id'
]

for col in numeric_cols:

    # Replace negative values with 0
    branches.loc[
        branches[col] < 0,
        col
    ] = 0

branches = (
    branches.fillna('Unknown')
)

# =========================
# CHECK NULL VALUES
# =========================

print("Null values after cleaning:\n")

null_values = branches.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# =========================
# CHECK NEGATIVE VALUES
# =========================

print("\nChecking negative values:\n")

numeric_check = branches.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_check:

    negative_count = (
        branches[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    branches[numeric_check] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# =========================
# SAVE CLEANED TABLE
# =========================

branches.to_sql(
    'branches_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

branch_id                    0
branch_name                  0
city                         0
state                        0
region                       0
branch_manager               0
opening_date                 0
branch_type                  0
claim_processing_capacity    0
dtype: int64

No null values present after cleaning.

Checking negative values:

branch_id : 0 negative values
claim_processing_capacity : 0 negative values

No negative values present after cleaning.

500

In [25]:
providers.head()

,provider_id,provider_name,provider_type,city,state,network_status,average_claim_amount,provider_risk_level,claim_inflation_flag
0,3001,Global Surveyor_3001,Hospital,Pune,Tamil Nadu,Out-of-Network,261234.18,High,b'\x00'
1,3002,Regional Surveyor_3002,Hospital,Chennai,Gujarat,In-Network,361268.01,High,b'\x00'
2,3003,National Clinic_3003,Hospital,Jaipur,West Bengal,Out-of-Network,326208.96,Medium,b'\x00'
3,3004,National Surveyor_3004,Garage,Hyderabad,Delhi,Out-of-Network,444848.07,Medium,b'\x00'
4,3005,National Clinic_3005,Surveyor,Bengaluru,Karnataka,In-Network,497717.80,Low,b'\x00'

In [26]:
# =========================
# PROVIDERS TABLE CLEANING
# =========================

providers = providers.drop_duplicates()

providers['provider_name'] = (
    providers['provider_name']
    .fillna('Unknown')
)

providers['provider_type'] = (
    providers['provider_type']
    .fillna('Unknown')
)

providers['city'] = (
    providers['city']
    .fillna('Unknown')
)
providers['claim_inflation_flag'] = np.where(
    providers['average_claim_amount'] > 1000000,
    1,
    0
).astype(int)

providers = providers.fillna('Unknown')
# =========================
# CHECK NULL VALUES
# =========================

print("Null values after cleaning:\n")

null_values = providers.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# =========================
# CHECK NEGATIVE VALUES
# =========================

print("\nChecking negative values:\n")

numeric_cols = providers.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_cols:

    negative_count = (
        providers[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    providers[numeric_cols] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# =========================
# SAVE CLEANED TABLE
# =========================

providers.to_sql(
    'providers_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

provider_id             0
provider_name           0
provider_type           0
city                    0
state                   0
network_status          0
average_claim_amount    0
provider_risk_level     0
claim_inflation_flag    0
dtype: int64

No null values present after cleaning.

Checking negative values:

provider_id : 0 negative values
average_claim_amount : 0 negative values
claim_inflation_flag : 0 negative values

No negative values present after cleaning.

5001

In [27]:
policy_renewals.head()

,renewal_id,policy_id,customer_id,renewal_due_date,renewal_date,renewal_status,renewal_premium,discount_offered,lapse_reason
0,6100001,5107297,139451.0,2023-04-03,2022-11-24,Lapsed,48263.92,4586.60,Claim Dissatisfaction
1,6100002,5071035,101330.0,2022-05-23,2022-09-05,Lapsed,23867.25,150.60,No Response
2,6100003,5241820,179925.0,2024-11-26,2022-12-19,Lapsed,46161.70,74.69,Competitor Offer
3,6100004,5213252,113050.0,2021-02-26,2024-07-06,Renewed,41383.39,3238.69,Claim Dissatisfaction
4,6100005,5081586,157962.0,2022-06-15,2022-02-11,Lapsed,10885.08,4134.54,Competitor Offer

In [28]:
# ===============================
# POLICY RENEWALS TABLE CLEANING
# ===============================

policy_renewals = (
    policy_renewals.drop_duplicates()
)

policy_renewals['renewal_status'] = (
    policy_renewals['renewal_status']
    .fillna('Unknown')
)

policy_renewals['lapse_reason'] = (
    policy_renewals['lapse_reason']
    .fillna('Unknown')
)

policy_renewals['renewal_due_date'] = pd.to_datetime(
    policy_renewals['renewal_due_date'],
    errors='coerce'
)

policy_renewals['renewal_date'] = pd.to_datetime(
    policy_renewals['renewal_date'],
    errors='coerce'
)
numeric_cols = [
    'renewal_id',
    'policy_id',
    'customer_id',
    'renewal_premium',
    'discount_offered'
]

for col in numeric_cols:

   

    policy_renewals.loc[
        policy_renewals[col] <= 0,
        col
    ] = 0

policy_renewals = (
    policy_renewals.fillna('Unknown')
)

policy_renewals.to_sql(
    'policy_renewals_cleaned',
    engine,
    if_exists='replace',
    index=False
)
# ===============================
# CHECK NULL VALUES
# ===============================

print("Null values after cleaning:\n")

null_values = policy_renewals.isnull().sum()

print(null_values)

if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")

# ===============================
# CHECK NEGATIVE VALUES
# ===============================

print("\nChecking negative values:\n")

numeric_check = policy_renewals.select_dtypes(
    include=['int64', 'float64']
).columns

for col in numeric_check:

    negative_count = (
        policy_renewals[col] < 0
    ).sum()

    print(f"{col} : {negative_count} negative values")

total_negative = (
    policy_renewals[numeric_check] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# ===============================
# SAVE CLEANED TABLE
# ===============================

policy_renewals.to_sql(
    'policy_renewals_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

renewal_id          0
policy_id           0
customer_id         0
renewal_due_date    0
renewal_date        0
renewal_status      0
renewal_premium     0
discount_offered    0
lapse_reason        0
dtype: int64

No null values present after cleaning.

Checking negative values:

renewal_id : 0 negative values
policy_id : 0 negative values
renewal_premium : 0 negative values
discount_offered : 0 negative values

No negative values present after cleaning.

100001

In [29]:
customer_complaints.head()

,complaint_id,customer_id,policy_id,claim_id,complaint_category,complaint_date,resolution_status,resolution_time_days,customer_sentiment
0,9300001,137167.0,5047584.0,9040701.0,Agent Issue,2024-11-07,Open,3,Positive
1,9300002,181801.0,5132682.0,NaN,Agent Issue,2022-09-07,Open,36,Negative
2,9300003,154296.0,5056849.0,9065087.0,Settlement Delay,2024-05-31,Resolved,31,Neutral
3,9300004,169739.0,5092842.0,9116917.0,Agent Issue,2024-06-10,Open,37,Negative
4,9300005,174581.0,5223124.0,9036779.0,Premium Dispute,2023-10-06,Resolved,8,Positive

In [30]:
# =================================
# CUSTOMER COMPLAINTS CLEANING
# =================================

customer_complaints = (
    customer_complaints.drop_duplicates()
)

# Missing claim_id
customer_complaints['claim_id'] = (
    customer_complaints['claim_id']
    .fillna(0)
    .astype(int)
)
customer_complaints['resolution_time_days'] = (
    customer_complaints['resolution_time_days']
    .fillna(0)
    .astype(int)
)
customer_complaints.loc[
    customer_complaints['resolution_time_days']<0,
    'resolution_time_days']=0
    

customer_complaints['complaint_category'] = (
    customer_complaints['complaint_category']
    .fillna('Unknown')
)
customer_complaints['customer_sentiment'] = (
    customer_complaints['customer_sentiment']
    .fillna('Unknown')
)
customer_complaints['resolution_status'] = (
    customer_complaints['resolution_status']
    .fillna('Unknown')
)

customer_complaints['complaint_date'] = pd.to_datetime(
    customer_complaints['complaint_date'],
    errors='coerce'
)
numeric_cols = [
    'complaint_id',
    'policy_id',
    'customer_id',
    'claim_id'
]

for col in numeric_cols:

    customer_complaints[col] = (
        customer_complaints[col].fillna(0)
    )

    customer_complaints.loc[
        customer_complaints[col] < 0,
        col
    ] = 0
customer_complaints = (
    customer_complaints.fillna('Unknown')
)

customer_complaints.to_sql(
    'customer_complaints_cleaned',
    engine,
    if_exists='replace',
    index=False
)

print("Null values after cleaning:\n")

null_values = customer_complaints.isnull().sum()

print(null_values)

# Check if any null values still exist
if null_values.sum() == 0:
    print("\nNo null values present after cleaning.")
else:
    print("\nSome null values are still present.")
# =================================
# CHECK NEGATIVE VALUES AFTER CLEANING
# =================================

print("Checking negative values:\n")

numeric_cols = customer_complaints.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    
    negative_count = (customer_complaints[col] < 0).sum()
    
    print(f"{col} : {negative_count} negative values")

# Final verification
total_negative = (
    customer_complaints[numeric_cols] < 0
).sum().sum()

if total_negative == 0:
    print("\nNo negative values present after cleaning.")
else:
    print("\nSome negative values are still present.")

# =================================
# SAVE CLEANED TABLE
# =================================

customer_complaints.to_sql(
    'customer_complaints_cleaned',
    engine,
    if_exists='replace',
    index=False
)

Null values after cleaning:

complaint_id            0
customer_id             0
policy_id               0
claim_id                0
complaint_category      0
complaint_date          0
resolution_status       0
resolution_time_days    0
customer_sentiment      0
dtype: int64

No null values present after cleaning.
Checking negative values:

complaint_id : 0 negative values
customer_id : 0 negative values
policy_id : 0 negative values
claim_id : 0 negative values
resolution_time_days : 0 negative values

No negative values present after cleaning.

60361

In [31]:
# Create folder path (optional)

import os

folder_path = "cleaned_final_files"

os.makedirs(folder_path, exist_ok=True)

# ============================================================
# EXPORT EACH TABLE
# ============================================================

branches.to_csv(
    f"{folder_path}/branches_cleaned.csv",
    index=False
)

agents.to_csv(
    f"{folder_path}/agents_cleaned.csv",
    index=False
)

providers.to_csv(
    f"{folder_path}/providers_cleaned.csv",
    index=False
)

customers.to_csv(
    f"{folder_path}/customers_cleaned.csv",
    index=False
)

policies.to_csv(
    f"{folder_path}/policies_cleaned.csv",
    index=False
)

claims.to_csv(
    f"{folder_path}/claims_cleaned.csv",
    index=False
)

claim_investigations.to_csv(
    f"{folder_path}/claim_investigations_cleaned.csv",
    index=False
)

payments.to_csv(
    f"{folder_path}/payments_cleaned.csv",
    index=False
)

policy_renewals.to_csv(
    f"{folder_path}/policy_renewals_cleaned.csv",
    index=False
)

customer_complaints.to_csv(
    f"{folder_path}/customer_complaints_cleaned.csv",
    index=False
)

print("All Cleaned Tables Exported Successfully!")

All Cleaned Tables Exported Successfully!